apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techtalks-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: techtalks-app.rockchico.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: techtalks-app
                port:
                  number: 3000